### ISSUE TITLE
Update python-telegram-bot to v14 and use the new MessageQueue

### ISSUE THREAD

**Issue by aelkheir** [e-caste/boggle-telegram-bot#53]
In the documentation for the function `telegram.ext.messagequeue.queuedmessage` in the source code, it says it's used with "send* methods". However when following the guide in [avoiding flood limits](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limitsurl) and replacing the `MQBot` to decorate `send_document` instead, it does not seem to work.

**Comment by e-caste** [comment]
`MessageQueue` is currently [deprecated](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Avoiding-flood-limits#messagequeue-from-user-perspective) and should be available in v14 of `python-telegram-bot`.  
I will use this issue as a reminder to update the library when the new major comes out.  
In the meantime, try to ask around on [their Telegram group](https://telegram.me/pythontelegrambotgroup) and let me know if you find a temporary fix.

**Comment by aelkheir** [comment]
Oh-Oh, Sorry I don't how this issue ended up here, I feel so stupid 😅. I meant to open it in PTB and switched tabs apparently. Yeah I think v 14 is still a work in progress, and they suggested to use `JobQueue` instead and it works like a charm.
