### ISSUE TITLE
Changing settings does not affect current game

### ISSUE THREAD

**Issue by lvps** [e-caste/boggle-telegram-bot#54]
1. /newgame
2. /join
3. /settings and change something
4. /startgame
5. The game starts... with the old settings

That's ok if the game has already started I guess, but it wasn't started yet

**Comment by e-caste** [comment]
I have tested this and I can't reproduce it. Maybe because I am the creator of the game? 🤔

**Comment by e-caste** [comment]
Superseded by #55
